window.IB_TOPICS={
"A.1":"Kinematics","A.2":"Forces and momentum","A.3":"Work, energy and power","A.4":"Rigid body mechanics","A.5":"Galilean and special relativity",
"B.1":"Thermal energy transfers","B.2":"Greenhouse effect","B.3":"Gas laws","B.4":"Thermodynamics","B.5":"Current and circuits",
"C.1":"Simple harmonic motion","C.2":"Wave model","C.3":"Wave phenomena","C.4":"Standing waves and resonance","C.5":"Doppler effect",
"D.1":"Gravitational fields","D.2":"Electric and magnetic fields","D.3":"Motion in electromagnetic fields","D.4":"Induction",
"E.1":"Structure of the atom","E.2":"Quantum physics","E.3":"Radioactive decay","E.4":"Fission","E.5":"Fusion and stars"};
window.IB_REFERENCES=[
  {
    "id": "M25-HL-P2-TZ1-01",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q1(a)(i)",
    "topic": "A.3",
    "marks": 1,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "work / kinetic-energy interpretation"
  },
  {
    "id": "M25-HL-P2-TZ1-02",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q1(a)(ii)",
    "topic": "A.3",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "work-energy / graph area"
  },
  {
    "id": "M25-HL-P2-TZ1-03",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q1(b)",
    "topic": "A.3",
    "marks": 3,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "power and motion relationship"
  },
  {
    "id": "M25-HL-P2-TZ1-04",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q2(a)",
    "topic": "D.1",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "Kepler third-law orbit comparison"
  },
  {
    "id": "M25-HL-P2-TZ1-05",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q2(b)",
    "topic": "D.1",
    "marks": 2,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "gravitational force and orbital motion"
  },
  {
    "id": "M25-HL-P2-TZ1-06",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q2(c)",
    "topic": "D.1",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "gravitational potential"
  },
  {
    "id": "M25-HL-P2-TZ1-07",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(a)(i)",
    "topic": "E.1",
    "marks": 1,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "strong nuclear interaction"
  },
  {
    "id": "M25-HL-P2-TZ1-08",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(a)(ii)",
    "topic": "E.1",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "closest approach / nuclear radius"
  },
  {
    "id": "M25-HL-P2-TZ1-09",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(b)(i)",
    "topic": "E.3",
    "marks": 1,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "decay constant"
  },
  {
    "id": "M25-HL-P2-TZ1-10",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(b)(ii)",
    "topic": "E.3",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "radioactive decay mass"
  },
  {
    "id": "M25-HL-P2-TZ1-11",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(c)",
    "topic": "E.1",
    "marks": 2,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "discrete nuclear energy levels / gamma emission"
  },
  {
    "id": "M25-HL-P2-TZ1-12",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q4(a)",
    "topic": "B.4",
    "marks": 2,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "microstates and entropy"
  },
  {
    "id": "M25-HL-P2-TZ1-13",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q4(b)",
    "topic": "B.4",
    "marks": 3,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "second law and entropy change"
  },
  {
    "id": "M25-HL-P2-TZ1-14",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(a)(i)",
    "topic": "C.5",
    "marks": 1,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "Doppler-effect direction"
  },
  {
    "id": "M25-HL-P2-TZ1-15",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(a)(ii)",
    "topic": "C.5",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "Doppler speed"
  },
  {
    "id": "M25-HL-P2-TZ1-16",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(b)(i)",
    "topic": "C.2",
    "marks": 1,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "wave speed, frequency and wavelength"
  },
  {
    "id": "M25-HL-P2-TZ1-17",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(b)(ii)",
    "topic": "C.3",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "path difference and interference"
  },
  {
    "id": "M25-HL-P2-TZ1-18",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(c)",
    "topic": "C.3",
    "marks": 3,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "refraction / critical-angle reasoning"
  },
  {
    "id": "M25-HL-P2-TZ1-19",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(a)",
    "topic": "D.3",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "charged-particle acceleration through potential"
  },
  {
    "id": "M25-HL-P2-TZ1-20",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(b)(i)",
    "topic": "D.3",
    "marks": 1,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "electric-force direction"
  },
  {
    "id": "M25-HL-P2-TZ1-21",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(b)(ii)",
    "topic": "D.3",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "electric force and acceleration"
  },
  {
    "id": "M25-HL-P2-TZ1-22",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(c)",
    "topic": "D.3",
    "marks": 3,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "motion in uniform electric field"
  },
  {
    "id": "M25-HL-P2-TZ1-23",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(d)",
    "topic": "D.3",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "velocity selector / magnetic field"
  },
  {
    "id": "M25-HL-P2-TZ1-24",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q7(a)(i)",
    "topic": "A.5",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "spacetime interval"
  },
  {
    "id": "M25-HL-P2-TZ1-25",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q7(a)(ii)",
    "topic": "A.5",
    "marks": 1,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "invariance across inertial frames"
  },
  {
    "id": "M25-HL-P2-TZ1-26",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q7(b)(i)",
    "topic": "A.5",
    "marks": 2,
    "type": "Graph",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "Lorentz-transformed axes"
  },
  {
    "id": "M25-HL-P2-TZ1-27",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q7(b)(ii)",
    "topic": "A.5",
    "marks": 1,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "relative speed from spacetime diagram"
  },
  {
    "id": "M25-HL-P2-TZ1-28",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(a)",
    "topic": "B.2",
    "marks": 1,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "solar radiation intensity"
  },
  {
    "id": "M25-HL-P2-TZ1-29",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(b)(i)",
    "topic": "B.2",
    "marks": 2,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "greenhouse-gas absorption and re-emission"
  },
  {
    "id": "M25-HL-P2-TZ1-30",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(b)(ii)",
    "topic": "B.2",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "planetary energy balance"
  },
  {
    "id": "M25-HL-P2-TZ1-31",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(b)(iii)",
    "topic": "B.2",
    "marks": 3,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "Stefan-Boltzmann / re-radiated intensity"
  },
  {
    "id": "M25-HL-P2-TZ1-32",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(c)",
    "topic": "E.5",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "stellar luminosity from solar intensity"
  },
  {
    "id": "M25-HL-P2-TZ1-33",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(d)(i)",
    "topic": "E.5",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "fusion mass defect and energy"
  },
  {
    "id": "M25-HL-P2-TZ1-34",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(d)(ii)",
    "topic": "E.5",
    "marks": 2,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "stellar hydrostatic equilibrium"
  },
  {
    "id": "M25-HL-P2-TZ1-35",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(d)(iii)",
    "topic": "E.5",
    "marks": 2,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "stellar spectra and helium evidence"
  },
  {
    "id": "M25-HL-P2-TZ1-36",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(e)(i)",
    "topic": "E.5",
    "marks": 1,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "stellar classification"
  },
  {
    "id": "M25-HL-P2-TZ1-37",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(e)(ii)",
    "topic": "E.5",
    "marks": 3,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "stellar fusion and evolution"
  },
  {
    "id": "M25-HL-P2-TZ1-38",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(a)",
    "topic": "C.1",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "spring equilibrium and elastic energy"
  },
  {
    "id": "M25-HL-P2-TZ1-39",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(b)(i)",
    "topic": "C.1",
    "marks": 2,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "spring motion and elastic potential energy"
  },
  {
    "id": "M25-HL-P2-TZ1-40",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(b)(ii)",
    "topic": "C.1",
    "marks": 2,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "energy transfers in oscillation"
  },
  {
    "id": "M25-HL-P2-TZ1-41",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(c)(i)",
    "topic": "C.1",
    "marks": 3,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "SHM amplitude from energy"
  },
  {
    "id": "M25-HL-P2-TZ1-42",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(c)(ii)",
    "topic": "C.1",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "maximum SHM speed"
  },
  {
    "id": "M25-HL-P2-TZ1-43",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(c)(iii)",
    "topic": "C.1",
    "marks": 2,
    "type": "Calculation",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "SHM energy at a later time"
  },
  {
    "id": "M25-HL-P2-TZ1-44",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(d)(i)",
    "topic": "D.4",
    "marks": 4,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "Faraday law factors affecting induced emf"
  },
  {
    "id": "M25-HL-P2-TZ1-45",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(d)(ii)",
    "topic": "D.4",
    "marks": 3,
    "type": "Explain",
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-hl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-hl.pdf",
    "notes": "Lenz law and energy dissipation"
  },
  {
    "id": "M25-SL-P2-TZ1-01",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q1(a)(i)",
    "topic": "A.3",
    "marks": 1,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "work done and force-distance graphs"
  },
  {
    "id": "M25-SL-P2-TZ1-02",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q1(a)(ii)",
    "topic": "A.3",
    "marks": 2,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "work-energy and final speed"
  },
  {
    "id": "M25-SL-P2-TZ1-03",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q1(b)",
    "topic": "A.3",
    "marks": 3,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "power and drag"
  },
  {
    "id": "M25-SL-P2-TZ1-04",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q2(a)",
    "topic": "D.1",
    "marks": 2,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "Kepler laws and orbital motion"
  },
  {
    "id": "M25-SL-P2-TZ1-05",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q2(b)",
    "topic": "D.1",
    "marks": 2,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "circular orbits and solar mass"
  },
  {
    "id": "M25-SL-P2-TZ1-06",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(a)",
    "topic": "B.5",
    "marks": 1,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "resistance from I-V behaviour"
  },
  {
    "id": "M25-SL-P2-TZ1-07",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(b)",
    "topic": "B.5",
    "marks": 1,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "non-ohmic behaviour"
  },
  {
    "id": "M25-SL-P2-TZ1-08",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(c)",
    "topic": "B.5",
    "marks": 1,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "series circuit"
  },
  {
    "id": "M25-SL-P2-TZ1-09",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(d)",
    "topic": "B.5",
    "marks": 2,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "emf in series circuit"
  },
  {
    "id": "M25-SL-P2-TZ1-10",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q4(a)",
    "topic": "C.2",
    "marks": 1,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "sound versus electromagnetic waves"
  },
  {
    "id": "M25-SL-P2-TZ1-11",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q4(b)(i)",
    "topic": "C.2",
    "marks": 1,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "travelling-wave relation"
  },
  {
    "id": "M25-SL-P2-TZ1-12",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q4(b)(ii)",
    "topic": "C.3",
    "marks": 2,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "interference and path difference"
  },
  {
    "id": "M25-SL-P2-TZ1-13",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q4(c)",
    "topic": "C.3",
    "marks": 3,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "refraction and total internal reflection"
  },
  {
    "id": "M25-SL-P2-TZ1-14",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(a)(i)",
    "topic": "D.3",
    "marks": 1,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "charged particle in electric field"
  },
  {
    "id": "M25-SL-P2-TZ1-15",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(a)(ii)",
    "topic": "D.3",
    "marks": 2,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "electron acceleration in uniform field"
  },
  {
    "id": "M25-SL-P2-TZ1-16",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(b)",
    "topic": "D.3",
    "marks": 3,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "projectile-like charged-particle motion"
  },
  {
    "id": "M25-SL-P2-TZ1-17",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(c)",
    "topic": "D.3",
    "marks": 2,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "velocity selector"
  },
  {
    "id": "M25-SL-P2-TZ1-18",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(a)",
    "topic": "B.2",
    "marks": 1,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "solar radiation intensity"
  },
  {
    "id": "M25-SL-P2-TZ1-19",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(b)(i)",
    "topic": "B.2",
    "marks": 2,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "greenhouse gas absorption and reradiation"
  },
  {
    "id": "M25-SL-P2-TZ1-20",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(b)(ii)",
    "topic": "B.2",
    "marks": 2,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "albedo and Earth energy balance"
  },
  {
    "id": "M25-SL-P2-TZ1-21",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(b)(iii)",
    "topic": "B.2",
    "marks": 3,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "atmospheric reradiation / energy balance"
  },
  {
    "id": "M25-SL-P2-TZ1-22",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(c)",
    "topic": "E.5",
    "marks": 2,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "solar luminosity"
  },
  {
    "id": "M25-SL-P2-TZ1-23",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(d)(i)",
    "topic": "E.5",
    "marks": 2,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "fusion energy"
  },
  {
    "id": "M25-SL-P2-TZ1-24",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(d)(ii)",
    "topic": "E.5",
    "marks": 2,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "stellar equilibrium"
  },
  {
    "id": "M25-SL-P2-TZ1-25",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(d)(iii)",
    "topic": "E.5",
    "marks": 2,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "stellar spectra / helium"
  },
  {
    "id": "M25-SL-P2-TZ1-26",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(e)(i)",
    "topic": "E.5",
    "marks": 1,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "H-R diagram / stellar classification"
  },
  {
    "id": "M25-SL-P2-TZ1-27",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(e)(ii)",
    "topic": "E.5",
    "marks": 3,
    "source": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-tz1-sl.pdf",
    "markscheme": "https://www.papersdaddy.com/ib/past-papers/sciences/physics/2025-may/physics-paper-2-markscheme-tz1-sl.pdf",
    "notes": "stellar evolution and nucleosynthesis"
  }
];