window.IB_TOPICS={
"A.1":"Kinematics","A.2":"Forces and momentum","A.3":"Work, energy and power","A.4":"Rigid body mechanics","A.5":"Galilean and special relativity",
"B.1":"Thermal energy transfers","B.2":"Greenhouse effect","B.3":"Gas laws","B.4":"Thermodynamics","B.5":"Current and circuits",
"C.1":"Simple harmonic motion","C.2":"Wave model","C.3":"Wave phenomena","C.4":"Standing waves and resonance","C.5":"Doppler effect",
"D.1":"Gravitational fields","D.2":"Electric and magnetic fields","D.3":"Motion in electromagnetic fields","D.4":"Induction",
"E.1":"Structure of the atom","E.2":"Quantum physics","E.3":"Radioactive decay","E.4":"Fission","E.5":"Fusion and stars"};
window.IB_REFERENCES=[
  {
    "id": "M25-HL-P2-TZ1-01",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q1(a)(i)",
    "topic": "A.3",
    "marks": 1,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "work / kinetic-energy interpretation"
  },
  {
    "id": "M25-HL-P2-TZ1-02",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q1(a)(ii)",
    "topic": "A.3",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "work-energy / graph area"
  },
  {
    "id": "M25-HL-P2-TZ1-03",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q1(b)",
    "topic": "A.3",
    "marks": 3,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "power and motion relationship"
  },
  {
    "id": "M25-HL-P2-TZ1-04",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q2(a)",
    "topic": "D.1",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Kepler third-law orbit comparison"
  },
  {
    "id": "M25-HL-P2-TZ1-05",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q2(b)",
    "topic": "D.1",
    "marks": 2,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "gravitational force and orbital motion"
  },
  {
    "id": "M25-HL-P2-TZ1-06",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q2(c)",
    "topic": "D.1",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "gravitational potential"
  },
  {
    "id": "M25-HL-P2-TZ1-07",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(a)(i)",
    "topic": "E.1",
    "marks": 1,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "strong nuclear interaction"
  },
  {
    "id": "M25-HL-P2-TZ1-08",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(a)(ii)",
    "topic": "E.1",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "closest approach / nuclear radius"
  },
  {
    "id": "M25-HL-P2-TZ1-09",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(b)(i)",
    "topic": "E.3",
    "marks": 1,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "decay constant"
  },
  {
    "id": "M25-HL-P2-TZ1-10",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(b)(ii)",
    "topic": "E.3",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "radioactive decay mass"
  },
  {
    "id": "M25-HL-P2-TZ1-11",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(c)",
    "topic": "E.1",
    "marks": 2,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "discrete nuclear energy levels / gamma emission"
  },
  {
    "id": "M25-HL-P2-TZ1-12",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q4(a)",
    "topic": "B.4",
    "marks": 2,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "microstates and entropy"
  },
  {
    "id": "M25-HL-P2-TZ1-13",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q4(b)",
    "topic": "B.4",
    "marks": 3,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "second law and entropy change"
  },
  {
    "id": "M25-HL-P2-TZ1-14",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(a)(i)",
    "topic": "C.5",
    "marks": 1,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Doppler-effect direction"
  },
  {
    "id": "M25-HL-P2-TZ1-15",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(a)(ii)",
    "topic": "C.5",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Doppler speed"
  },
  {
    "id": "M25-HL-P2-TZ1-16",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(b)(i)",
    "topic": "C.2",
    "marks": 1,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "wave speed, frequency and wavelength"
  },
  {
    "id": "M25-HL-P2-TZ1-17",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(b)(ii)",
    "topic": "C.3",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "path difference and interference"
  },
  {
    "id": "M25-HL-P2-TZ1-18",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(c)",
    "topic": "C.3",
    "marks": 3,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "refraction / critical-angle reasoning"
  },
  {
    "id": "M25-HL-P2-TZ1-19",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(a)",
    "topic": "D.3",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "charged-particle acceleration through potential"
  },
  {
    "id": "M25-HL-P2-TZ1-20",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(b)(i)",
    "topic": "D.3",
    "marks": 1,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "electric-force direction"
  },
  {
    "id": "M25-HL-P2-TZ1-21",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(b)(ii)",
    "topic": "D.3",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "electric force and acceleration"
  },
  {
    "id": "M25-HL-P2-TZ1-22",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(c)",
    "topic": "D.3",
    "marks": 3,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "motion in uniform electric field"
  },
  {
    "id": "M25-HL-P2-TZ1-23",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(d)",
    "topic": "D.3",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "velocity selector / magnetic field"
  },
  {
    "id": "M25-HL-P2-TZ1-24",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q7(a)(i)",
    "topic": "A.5",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "spacetime interval"
  },
  {
    "id": "M25-HL-P2-TZ1-25",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q7(a)(ii)",
    "topic": "A.5",
    "marks": 1,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "invariance across inertial frames"
  },
  {
    "id": "M25-HL-P2-TZ1-26",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q7(b)(i)",
    "topic": "A.5",
    "marks": 2,
    "type": "Graph",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Lorentz-transformed axes"
  },
  {
    "id": "M25-HL-P2-TZ1-27",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q7(b)(ii)",
    "topic": "A.5",
    "marks": 1,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "relative speed from spacetime diagram"
  },
  {
    "id": "M25-HL-P2-TZ1-28",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(a)",
    "topic": "B.2",
    "marks": 1,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "solar radiation intensity"
  },
  {
    "id": "M25-HL-P2-TZ1-29",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(b)(i)",
    "topic": "B.2",
    "marks": 2,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "greenhouse-gas absorption and re-emission"
  },
  {
    "id": "M25-HL-P2-TZ1-30",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(b)(ii)",
    "topic": "B.2",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "planetary energy balance"
  },
  {
    "id": "M25-HL-P2-TZ1-31",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(b)(iii)",
    "topic": "B.2",
    "marks": 3,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Stefan-Boltzmann / re-radiated intensity"
  },
  {
    "id": "M25-HL-P2-TZ1-32",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(c)",
    "topic": "E.5",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "stellar luminosity from solar intensity"
  },
  {
    "id": "M25-HL-P2-TZ1-33",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(d)(i)",
    "topic": "E.5",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "fusion mass defect and energy"
  },
  {
    "id": "M25-HL-P2-TZ1-34",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(d)(ii)",
    "topic": "E.5",
    "marks": 2,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "stellar hydrostatic equilibrium"
  },
  {
    "id": "M25-HL-P2-TZ1-35",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(d)(iii)",
    "topic": "E.5",
    "marks": 2,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "stellar spectra and helium evidence"
  },
  {
    "id": "M25-HL-P2-TZ1-36",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(e)(i)",
    "topic": "E.5",
    "marks": 1,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "stellar classification"
  },
  {
    "id": "M25-HL-P2-TZ1-37",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q8(e)(ii)",
    "topic": "E.5",
    "marks": 3,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "stellar fusion and evolution"
  },
  {
    "id": "M25-HL-P2-TZ1-38",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(a)",
    "topic": "C.1",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "spring equilibrium and elastic energy"
  },
  {
    "id": "M25-HL-P2-TZ1-39",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(b)(i)",
    "topic": "C.1",
    "marks": 2,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "spring motion and elastic potential energy"
  },
  {
    "id": "M25-HL-P2-TZ1-40",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(b)(ii)",
    "topic": "C.1",
    "marks": 2,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "energy transfers in oscillation"
  },
  {
    "id": "M25-HL-P2-TZ1-41",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(c)(i)",
    "topic": "C.1",
    "marks": 3,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "SHM amplitude from energy"
  },
  {
    "id": "M25-HL-P2-TZ1-42",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(c)(ii)",
    "topic": "C.1",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "maximum SHM speed"
  },
  {
    "id": "M25-HL-P2-TZ1-43",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(c)(iii)",
    "topic": "C.1",
    "marks": 2,
    "type": "Calculation",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "SHM energy at a later time"
  },
  {
    "id": "M25-HL-P2-TZ1-44",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(d)(i)",
    "topic": "D.4",
    "marks": 4,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Faraday law factors affecting induced emf"
  },
  {
    "id": "M25-HL-P2-TZ1-45",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q9(d)(ii)",
    "topic": "D.4",
    "marks": 3,
    "type": "Explain",
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Lenz law and energy dissipation"
  },
  {
    "id": "M25-SL-P2-TZ1-01",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q1(a)(i)",
    "topic": "A.3",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "work done and force-distance graphs"
  },
  {
    "id": "M25-SL-P2-TZ1-02",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q1(a)(ii)",
    "topic": "A.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "work-energy and final speed"
  },
  {
    "id": "M25-SL-P2-TZ1-03",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q1(b)",
    "topic": "A.3",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "power and drag"
  },
  {
    "id": "M25-SL-P2-TZ1-04",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q2(a)",
    "topic": "D.1",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "Kepler laws and orbital motion"
  },
  {
    "id": "M25-SL-P2-TZ1-05",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q2(b)",
    "topic": "D.1",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "circular orbits and solar mass"
  },
  {
    "id": "M25-SL-P2-TZ1-06",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(a)",
    "topic": "B.5",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "resistance from I-V behaviour"
  },
  {
    "id": "M25-SL-P2-TZ1-07",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(b)",
    "topic": "B.5",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "non-ohmic behaviour"
  },
  {
    "id": "M25-SL-P2-TZ1-08",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(c)",
    "topic": "B.5",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "series circuit"
  },
  {
    "id": "M25-SL-P2-TZ1-09",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q3(d)",
    "topic": "B.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "emf in series circuit"
  },
  {
    "id": "M25-SL-P2-TZ1-10",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q4(a)",
    "topic": "C.2",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "sound versus electromagnetic waves"
  },
  {
    "id": "M25-SL-P2-TZ1-11",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q4(b)(i)",
    "topic": "C.2",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "travelling-wave relation"
  },
  {
    "id": "M25-SL-P2-TZ1-12",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q4(b)(ii)",
    "topic": "C.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "interference and path difference"
  },
  {
    "id": "M25-SL-P2-TZ1-13",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q4(c)",
    "topic": "C.3",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "refraction and total internal reflection"
  },
  {
    "id": "M25-SL-P2-TZ1-14",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(a)(i)",
    "topic": "D.3",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "charged particle in electric field"
  },
  {
    "id": "M25-SL-P2-TZ1-15",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(a)(ii)",
    "topic": "D.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "electron acceleration in uniform field"
  },
  {
    "id": "M25-SL-P2-TZ1-16",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(b)",
    "topic": "D.3",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "projectile-like charged-particle motion"
  },
  {
    "id": "M25-SL-P2-TZ1-17",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q5(c)",
    "topic": "D.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "velocity selector"
  },
  {
    "id": "M25-SL-P2-TZ1-18",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(a)",
    "topic": "B.2",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "solar radiation intensity"
  },
  {
    "id": "M25-SL-P2-TZ1-19",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(b)(i)",
    "topic": "B.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "greenhouse gas absorption and reradiation"
  },
  {
    "id": "M25-SL-P2-TZ1-20",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(b)(ii)",
    "topic": "B.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "albedo and Earth energy balance"
  },
  {
    "id": "M25-SL-P2-TZ1-21",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(b)(iii)",
    "topic": "B.2",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "atmospheric reradiation / energy balance"
  },
  {
    "id": "M25-SL-P2-TZ1-22",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(c)",
    "topic": "E.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "solar luminosity"
  },
  {
    "id": "M25-SL-P2-TZ1-23",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(d)(i)",
    "topic": "E.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "fusion energy"
  },
  {
    "id": "M25-SL-P2-TZ1-24",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(d)(ii)",
    "topic": "E.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "stellar equilibrium"
  },
  {
    "id": "M25-SL-P2-TZ1-25",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(d)(iii)",
    "topic": "E.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "stellar spectra / helium"
  },
  {
    "id": "M25-SL-P2-TZ1-26",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(e)(i)",
    "topic": "E.5",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "H-R diagram / stellar classification"
  },
  {
    "id": "M25-SL-P2-TZ1-27",
    "year": 2025,
    "session": "May",
    "level": "SL",
    "paper": "Paper 2",
    "timezone": "TZ1",
    "question": "Q6(e)(ii)",
    "topic": "E.5",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_SL/",
    "notes": "stellar evolution and nucleosynthesis"
  },
  {
    "id": "M25-HL-P2-TZ3-01",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q1(a)",
    "topic": "A.2",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "friction"
  },
  {
    "id": "M25-HL-P2-TZ3-02",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q1(b)",
    "topic": "A.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Newton laws"
  },
  {
    "id": "M25-HL-P2-TZ3-03",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q1(c)",
    "topic": "A.3",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "work-energy"
  },
  {
    "id": "M25-HL-P2-TZ3-04",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q1(d)(i)",
    "topic": "A.4",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "torque"
  },
  {
    "id": "M25-HL-P2-TZ3-05",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q1(d)(ii)",
    "topic": "A.2",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "friction and tipping"
  },
  {
    "id": "M25-HL-P2-TZ3-06",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q2(a)",
    "topic": "A.5",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "spacetime diagram"
  },
  {
    "id": "M25-HL-P2-TZ3-07",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q2(b)",
    "topic": "A.5",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "light paths in spacetime"
  },
  {
    "id": "M25-HL-P2-TZ3-08",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q2(c)",
    "topic": "A.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "relativity of simultaneity"
  },
  {
    "id": "M25-HL-P2-TZ3-09",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q2(d)",
    "topic": "A.5",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Lorentz transformation"
  },
  {
    "id": "M25-HL-P2-TZ3-10",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q3(a)",
    "topic": "B.4",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "thermodynamic cycle"
  },
  {
    "id": "M25-HL-P2-TZ3-11",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q3(b)",
    "topic": "B.4",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "adiabatic work"
  },
  {
    "id": "M25-HL-P2-TZ3-12",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q3(c)",
    "topic": "B.4",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "heat engine"
  },
  {
    "id": "M25-HL-P2-TZ3-13",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q4(a)",
    "topic": "C.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "sound and light waves"
  },
  {
    "id": "M25-HL-P2-TZ3-14",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q4(b)(i)",
    "topic": "C.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "wavelength and period"
  },
  {
    "id": "M25-HL-P2-TZ3-15",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q4(b)(ii)",
    "topic": "C.2",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "wave speed"
  },
  {
    "id": "M25-HL-P2-TZ3-16",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q4(c)(i)",
    "topic": "C.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Doppler effect sound"
  },
  {
    "id": "M25-HL-P2-TZ3-17",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q4(c)(ii)",
    "topic": "C.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Doppler calculation"
  },
  {
    "id": "M25-HL-P2-TZ3-18",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q4(c)(iii)",
    "topic": "C.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "redshift"
  },
  {
    "id": "M25-HL-P2-TZ3-19",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q5(a)(i)",
    "topic": "E.3",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "alpha decay"
  },
  {
    "id": "M25-HL-P2-TZ3-20",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q5(a)(ii)",
    "topic": "E.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "decay energy"
  },
  {
    "id": "M25-HL-P2-TZ3-21",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q5(a)(iii)",
    "topic": "E.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "energy sharing in decay"
  },
  {
    "id": "M25-HL-P2-TZ3-22",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q5(b)(i)",
    "topic": "E.1",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Rutherford scattering"
  },
  {
    "id": "M25-HL-P2-TZ3-23",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q5(b)(ii)",
    "topic": "E.1",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "scattering interpretation"
  },
  {
    "id": "M25-HL-P2-TZ3-24",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q5(b)(iii)",
    "topic": "E.1",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "closest approach"
  },
  {
    "id": "M25-HL-P2-TZ3-25",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q5(b)(iv)",
    "topic": "E.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "nuclear radius ratio"
  },
  {
    "id": "M25-HL-P2-TZ3-26",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q6(a)",
    "topic": "E.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "photoelectric effect graph"
  },
  {
    "id": "M25-HL-P2-TZ3-27",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q6(b)",
    "topic": "E.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "stopping voltage"
  },
  {
    "id": "M25-HL-P2-TZ3-28",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q6(c)",
    "topic": "E.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "photoelectric threshold"
  },
  {
    "id": "M25-HL-P2-TZ3-29",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q7(a)(i)",
    "topic": "A.2",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "buoyancy"
  },
  {
    "id": "M25-HL-P2-TZ3-30",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q7(a)(ii)",
    "topic": "A.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "floating condition"
  },
  {
    "id": "M25-HL-P2-TZ3-31",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q7(b)",
    "topic": "C.1",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "SHM period/frequency"
  },
  {
    "id": "M25-HL-P2-TZ3-32",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q7(c)(i)",
    "topic": "B.1",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "particle model and density"
  },
  {
    "id": "M25-HL-P2-TZ3-33",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q7(c)(ii)",
    "topic": "B.1",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "water density anomaly"
  },
  {
    "id": "M25-HL-P2-TZ3-34",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q7(d)(i)",
    "topic": "A.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "buoyancy and iceberg"
  },
  {
    "id": "M25-HL-P2-TZ3-35",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q7(d)(ii)",
    "topic": "A.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "inelastic collision"
  },
  {
    "id": "M25-HL-P2-TZ3-36",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q7(e)(i)",
    "topic": "B.1",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "thermal conduction"
  },
  {
    "id": "M25-HL-P2-TZ3-37",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q7(e)(ii)",
    "topic": "B.1",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "latent heat"
  },
  {
    "id": "M25-HL-P2-TZ3-38",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q7(e)(iii)",
    "topic": "B.1",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "conduction through ice"
  },
  {
    "id": "M25-HL-P2-TZ3-39",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q7(e)(iv)",
    "topic": "B.1",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "water density anomaly and life"
  },
  {
    "id": "M25-HL-P2-TZ3-40",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q8(a)(i)",
    "topic": "D.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "force on current-carrying conductor"
  },
  {
    "id": "M25-HL-P2-TZ3-41",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q8(a)(ii)",
    "topic": "D.3",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "magnetic-force direction"
  },
  {
    "id": "M25-HL-P2-TZ3-42",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q8(b)(i)",
    "topic": "D.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "field of parallel wire"
  },
  {
    "id": "M25-HL-P2-TZ3-43",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q8(b)(ii)",
    "topic": "D.3",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "permeability base units"
  },
  {
    "id": "M25-HL-P2-TZ3-44",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q8(c)(i)",
    "topic": "D.4",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "electromagnetic induction"
  },
  {
    "id": "M25-HL-P2-TZ3-45",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q8(c)(ii)",
    "topic": "D.4",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "induced emf"
  },
  {
    "id": "M25-HL-P2-TZ3-46",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q8(c)(iii)",
    "topic": "D.4",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Lenz law direction"
  },
  {
    "id": "M25-HL-P2-TZ3-47",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q8(d)",
    "topic": "D.4",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "rotating coil emf"
  },
  {
    "id": "M25-HL-P2-TZ3-48",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q8(e)(i)",
    "topic": "D.3",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "electron in magnetic field"
  },
  {
    "id": "M25-HL-P2-TZ3-49",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ3",
    "question": "Q8(e)(ii)",
    "topic": "D.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "orbit radius change"
  },
  {
    "id": "M25-HL-P2-TZ2-01",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q1(a)",
    "topic": "A.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "elastic collision / momentum and kinetic energy"
  },
  {
    "id": "M25-HL-P2-TZ2-02",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q1(b)(i)",
    "topic": "A.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "impulse and average force"
  },
  {
    "id": "M25-HL-P2-TZ2-03",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q1(b)(ii)",
    "topic": "A.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "average power"
  },
  {
    "id": "M25-HL-P2-TZ2-04",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q1(b)(iii)",
    "topic": "A.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "elastic potential energy"
  },
  {
    "id": "M25-HL-P2-TZ2-05",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q2(a)",
    "topic": "B.1",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "thermal conduction mechanism"
  },
  {
    "id": "M25-HL-P2-TZ2-06",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q2(b)",
    "topic": "B.1",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "rate of thermal energy transfer"
  },
  {
    "id": "M25-HL-P2-TZ2-07",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q2(c)(i)",
    "topic": "B.1",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "cooling curve gradient"
  },
  {
    "id": "M25-HL-P2-TZ2-08",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q2(c)(ii)",
    "topic": "B.3",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "ideal gas relation with changing molecule number"
  },
  {
    "id": "M25-HL-P2-TZ2-09",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q2(d)",
    "topic": "B.4",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "second law of thermodynamics"
  },
  {
    "id": "M25-HL-P2-TZ2-10",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q3(a)",
    "topic": "D.2",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "uniform electric field"
  },
  {
    "id": "M25-HL-P2-TZ2-11",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q3(b)(i)",
    "topic": "D.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "charged-particle acceleration in electric field"
  },
  {
    "id": "M25-HL-P2-TZ2-12",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q3(b)(ii)",
    "topic": "D.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "motion in electric field"
  },
  {
    "id": "M25-HL-P2-TZ2-13",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q3(b)(iii)",
    "topic": "D.3",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "energy gained through potential difference"
  },
  {
    "id": "M25-HL-P2-TZ2-14",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q3(c)",
    "topic": "D.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "velocity selector"
  },
  {
    "id": "M25-HL-P2-TZ2-15",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q3(d)",
    "topic": "D.3",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "electron path in crossed fields"
  },
  {
    "id": "M25-HL-P2-TZ2-16",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q5(a)",
    "topic": "E.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Compton scattering and photon model"
  },
  {
    "id": "M25-HL-P2-TZ2-17",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q5(b)",
    "topic": "E.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Compton wavelength shift"
  },
  {
    "id": "M25-HL-P2-TZ2-18",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q5(c)(i)",
    "topic": "E.2",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "scattered photon energy"
  },
  {
    "id": "M25-HL-P2-TZ2-19",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q5(c)(ii)",
    "topic": "E.2",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "recoil electron kinetic energy"
  },
  {
    "id": "M25-HL-P2-TZ2-20",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q5(c)(iii)",
    "topic": "E.2",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Compton scattering angle"
  },
  {
    "id": "M25-HL-P2-TZ2-21",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q6(a)",
    "topic": "A.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "time dilation / Lorentz factor"
  },
  {
    "id": "M25-HL-P2-TZ2-22",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q6(b)(i)",
    "topic": "A.5",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "light world-line on spacetime diagram"
  },
  {
    "id": "M25-HL-P2-TZ2-23",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q6(b)(ii)",
    "topic": "A.5",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "spacetime interval / travel time"
  },
  {
    "id": "M25-HL-P2-TZ2-24",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q7(a)(i)",
    "topic": "E.5",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "conditions for stellar fusion"
  },
  {
    "id": "M25-HL-P2-TZ2-25",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q7(a)(ii)",
    "topic": "E.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "stellar hydrostatic equilibrium"
  },
  {
    "id": "M25-HL-P2-TZ2-26",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q7(b)",
    "topic": "E.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "proton-proton chain energy"
  },
  {
    "id": "M25-HL-P2-TZ2-27",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q7(c)(i)",
    "topic": "E.5",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "main-sequence lifetime"
  },
  {
    "id": "M25-HL-P2-TZ2-28",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q7(c)(ii)",
    "topic": "E.5",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "stellar-lifetime assumption"
  },
  {
    "id": "M25-HL-P2-TZ2-29",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q7(c)(iii)",
    "topic": "E.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "mass loss by stellar radiation"
  },
  {
    "id": "M25-HL-P2-TZ2-30",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q7(d)",
    "topic": "E.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "Wien law and stellar spectrum"
  },
  {
    "id": "M25-HL-P2-TZ2-31",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q7(e)(i)",
    "topic": "C.5",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "stellar Doppler shift"
  },
  {
    "id": "M25-HL-P2-TZ2-32",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 2",
    "timezone": "TZ2",
    "question": "Q7(e)(ii)",
    "topic": "C.5",
    "marks": 3,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "rotation period from Doppler shift"
  },
  {
    "id": "M25-HL-P1B-TZ1-01",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1B",
    "timezone": "TZ1",
    "question": "Q1(a)",
    "topic": "B.1",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "measurement technique for volume"
  },
  {
    "id": "M25-HL-P1B-TZ1-02",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1B",
    "timezone": "TZ1",
    "question": "Q1(b)(i)",
    "topic": "B.1",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "density and uncertainty"
  },
  {
    "id": "M25-HL-P1B-TZ1-03",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1B",
    "timezone": "TZ1",
    "question": "Q1(b)(ii)",
    "topic": "B.1",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "SI conversion and precision"
  },
  {
    "id": "M25-HL-P1B-TZ1-04",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1B",
    "timezone": "TZ1",
    "question": "Q1(c)",
    "topic": "B.1",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "density-temperature data and conclusion"
  },
  {
    "id": "M25-HL-P1B-TZ1-05",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1B",
    "timezone": "TZ1",
    "question": "Q2(a)",
    "topic": "C.3",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "optical alignment / refraction"
  },
  {
    "id": "M25-HL-P1B-TZ1-06",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1B",
    "timezone": "TZ1",
    "question": "Q2(b)(i)",
    "topic": "C.3",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "angle of refraction measurement"
  },
  {
    "id": "M25-HL-P1B-TZ1-07",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1B",
    "timezone": "TZ1",
    "question": "Q2(b)(ii)",
    "topic": "C.3",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "refraction data processing"
  },
  {
    "id": "M25-HL-P1B-TZ1-08",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1B",
    "timezone": "TZ1",
    "question": "Q2(c)(i)",
    "topic": "C.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "graph gradient for refractive index"
  },
  {
    "id": "M25-HL-P1B-TZ1-09",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1B",
    "timezone": "TZ1",
    "question": "Q2(c)(ii)",
    "topic": "C.3",
    "marks": 1,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "maximum-gradient uncertainty line"
  },
  {
    "id": "M25-HL-P1B-TZ1-10",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1B",
    "timezone": "TZ1",
    "question": "Q2(c)(iii)",
    "topic": "C.3",
    "marks": 2,
    "source": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "markscheme": "https://dynamicrepo.sbs/IB%20PAST%20PAPERS%20-%20SUBJECT/Group%204%20-%20Sciences/Physics_HL/",
    "notes": "refractive index with uncertainty"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q01",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q1",
    "topic": "A.1",
    "marks": 1,
    "page": 3,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Instantaneous velocity"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q02",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q2",
    "topic": "A.1",
    "marks": 1,
    "page": 3,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Acceleration-time graph and speed"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q03",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q3",
    "topic": "A.2",
    "marks": 1,
    "page": 4,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Force and acceleration"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q04",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q4",
    "topic": "A.2",
    "marks": 1,
    "page": 4,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Buoyancy force"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q05",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q5",
    "topic": "A.4",
    "marks": 1,
    "page": 5,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Angular velocity"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q06",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q6",
    "topic": "A.2",
    "marks": 1,
    "page": 5,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Impulse and kinetic energy"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q07",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q7",
    "topic": "A.4",
    "marks": 1,
    "page": 5,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Angular momentum"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q08",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q8",
    "topic": "A.4",
    "marks": 1,
    "page": 6,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Moment of inertia"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q09",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q9",
    "topic": "A.5",
    "marks": 1,
    "page": 6,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Relativistic velocity addition"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q10",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q10",
    "topic": "B.1",
    "marks": 1,
    "page": 7,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Latent heat and melting"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q11",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q11",
    "topic": "B.2",
    "marks": 1,
    "page": 7,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Enhanced greenhouse effect"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q12",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q12",
    "topic": "B.4",
    "marks": 1,
    "page": 8,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Rapid gas compression and molecular energy"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q13",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q13",
    "topic": "B.4",
    "marks": 1,
    "page": 8,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Carnot cycle"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q14",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q14",
    "topic": "B.5",
    "marks": 1,
    "page": 9,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Equivalent resistance"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q15",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q15",
    "topic": "B.5",
    "marks": 1,
    "page": 10,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Current from moving surface charge"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q16",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q16",
    "topic": "B.5",
    "marks": 1,
    "page": 10,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Resistivity and geometry"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q17",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q17",
    "topic": "C.1",
    "marks": 1,
    "page": 11,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Spring-mass time period"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q18",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q18",
    "topic": "C.2",
    "marks": 1,
    "page": 12,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Wave frequency and amplitude"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q19",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q19",
    "topic": "C.1",
    "marks": 1,
    "page": 13,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "SHM speed"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q20",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q20",
    "topic": "C.3",
    "marks": 1,
    "page": 14,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Refraction through parallel layers"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q21",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q21",
    "topic": "C.3",
    "marks": 1,
    "page": 15,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Double-slit interference and diffraction envelope"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q22",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q22",
    "topic": "C.4",
    "marks": 1,
    "page": 15,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Standing wave in a closed pipe"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q23",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q23",
    "topic": "C.3",
    "marks": 1,
    "page": 16,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Diffraction grating maxima"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q24",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q24",
    "topic": "D.1",
    "marks": 1,
    "page": 16,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Gravitational field strength"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q25",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q25",
    "topic": "D.1",
    "marks": 1,
    "page": 17,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Gravitational potential graph"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q26",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q26",
    "topic": "D.2",
    "marks": 1,
    "page": 17,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Electromagnetic constants in SI units"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q27",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q27",
    "topic": "D.2",
    "marks": 1,
    "page": 18,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Electric field between parallel plates"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q28",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q28",
    "topic": "D.2",
    "marks": 1,
    "page": 18,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Force on current-carrying wire"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q29",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q29",
    "topic": "D.2",
    "marks": 1,
    "page": 19,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Magnetic effect on a current loop"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q30",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q30",
    "topic": "E.1",
    "marks": 1,
    "page": 19,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Quantization of electric charge"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q31",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q31",
    "topic": "D.4",
    "marks": 1,
    "page": 20,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Rotating coil and induced emf"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q32",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q32",
    "topic": "E.1",
    "marks": 1,
    "page": 20,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Nuclear notation"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q33",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q33",
    "topic": "E.1",
    "marks": 1,
    "page": 21,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Nuclear density"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q34",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q34",
    "topic": "E.2",
    "marks": 1,
    "page": 21,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Photoelectric effect"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q35",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q35",
    "topic": "E.2",
    "marks": 1,
    "page": 22,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Compton scattering"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q36",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q36",
    "topic": "E.3",
    "marks": 1,
    "page": 22,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Radioactive emissions in fields"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q37",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q37",
    "topic": "E.3",
    "marks": 1,
    "page": 22,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Decay sequence and isotopes"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q38",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q38",
    "topic": "E.4",
    "marks": 1,
    "page": 23,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Nuclear reactor moderator"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q39",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q39",
    "topic": "E.4",
    "marks": 1,
    "page": 23,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Criticality and neutron balance"
  },
  {
    "id": "M25-HL-P1A-TZ1-Q40",
    "year": 2025,
    "session": "May",
    "level": "HL",
    "paper": "Paper 1A",
    "timezone": "TZ1",
    "question": "Q40",
    "topic": "E.5",
    "marks": 1,
    "page": 23,
    "sourceFile": "Physics_paper_1A_TZ1_HL.pdf",
    "source": "",
    "markscheme": "",
    "notes": "Stellar parallax"
  }
];